apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: 'harbor.jq.cn'
      http:
        paths:
          - backend:
              serviceName: harbor
              servicePort: 80
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: ops
  labels:
    app: harbor
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: harbor
  namespace: ops
subsets:
  - addresses:
      - ip: 192.168.123.176
    ports:
      - port: 80