apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpldapadmin
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: ldap.jq.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: phpldapadmin
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: ops
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: phpldapadmin
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          imagePullPolicy: IfNotPresent
          image: osixia/phpldapadmin:0.8.0
          ports:
            - containerPort: 80
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: 'openldap'
            - name: PHPLDAPADMIN_HTTPS
              value: 'false'