apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zkui
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
    - hosts:
        - 'zkui.shixhsit.com'
    - secretName: 'ssl-sxh'
  rules:
    - host: 'zkui.shixhsit.com'
      http:
        paths:
          - backend:
              serviceName: zkui
              servicePort: 9090
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: zkui
  namespace: ops
  labels:
    app: zkui
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: zkui
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: zkui
  namespace: ops
  labels:
    app: zkui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zkui
  template:
    metadata:
      labels:
        app: zkui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.shixh.com/group
                    operator: In
                    values:
                      - ops
      containers:
        - name: zkui
          imagePullPolicy: IfNotPresent
          image: harbor.shixhlocal.com/library/zkui:k8s
          ports:
            - containerPort: 9090