apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nacos
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/app-root: /nacos/
spec:
  rules:
    - host: nacos.jq.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: nacos
              servicePort: 8848
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: ops
  labels:
    app: nacos
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8848"
spec:
  ports:
    - protocol: TCP
      port: 8848
      targetPort: 8848
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: nacos
  namespace: ops
subsets:
  - addresses:
      - ip: 192.168.123.176
    ports:
      - port: 8848