apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: prometheus.shixh.com
      http:
        paths:
          - path: '/'
            backend:
              serviceName: prometheus
              servicePort: 9090