image:
  repository: "docker.elastic.co/kibana/kibana"
  tag: "6.7.0"

serviceAccount:
  create: true

files:
  kibana.yml:
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: http://elasticsearch-client:9200

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/server-snippet: |
      set $agentflag 0;

      if ($http_user_agent ~* "(Mobile)" ){
        set $agentflag 1;
      }

      if ( $agentflag = 1 ) {
        return 301 https://m.example.com;
      }
  path: /
  hosts:
    - kibana.shixhsit.com
#  tls:
#    - secretName: ssl-sxh
#      hosts:
#        - kibana.shixhsit.com

#---设置资源限制---
#resources:
#  limits:
#    cpu: '1'
#    memory: 4Gi
#  requests:
#    cpu: '1'
#    memory: 4Gi

dashboardImport:
  enabled: false
  xpackauth:
    enabled: true
    username: 'admin'
    password: 'admin'

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.shixh.com/group
              operator: In
              values:
                - ops