# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "6.7.0"

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch"
  tag: "6.7.0"

cluster:
  name: "elasticsearch"
  xpackEnable: true
  additionalJavaOpts: ""

  config:
    http.cors.enabled: true
    http.cors.allow-origin: "*"

  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"
  # List of plugins to install via dedicated init container
  plugins: []
    # - ingest-attachment
  # - mapper-size


client:
  name: client
  replicas: 1
  serviceType: ClusterIP
  heapSize: "512m"
  additionalJavaOpts: "-XX:MaxRAM=512m"
  antiAffinity: "soft"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.shixh.com/group
              operator: In
              values:
                - ops
  resources:
    limits:
      cpu: "0.5"
      memory: "4Gi"
    requests:
      cpu: "0.5"
      memory: "4Gi"
  hooks: {}
    ## (string) Script to execute prior the client pod stops.
    # preStop: |-

    ## (string) Script to execute after the client pod starts.
  # postStart: |-
  ingress:
    enabled: true
    # user: NAME
    # password: PASSWORD
    annotations:
      kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - es.shixhsit.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "512m"
  additionalJavaOpts: "-XX:MaxRAM=512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "10Gi"
    storageClass: "nfs-client"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.shixh.com/group
              operator: In
              values:
                - ops
  resources:
    limits:
      cpu: "0.5"
      memory: "2Gi"
    requests:
      cpu: "0.5"
      memory: "2Gi"

data:
  name: data
  exposeHttp: false
  replicas: 2
  heapSize: "1536m"
  additionalJavaOpts: "-XX:MaxRAM=1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "500Gi"
    storageClass: "nfs-client"
  readinessProbe:
    httpGet:
      path: /_cluster/health?local=true
      port: 9200
    initialDelaySeconds: 5
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k8s.shixh.com/group
              operator: In
              values:
                - ops
  resources:
    limits:
      cpu: "0.5"
      memory: "4Gi"
    requests:
      cpu: "0.5"
      memory: "4Gi"