apiVersion: v1
kind: PersistentVolume
metadata:
  name: jumpserver-pv
  namespace: ops
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /jumpserver
    server: 172.16.16.8
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jumpserver-pvc
  namespace: ops
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi