apiVersion: v1
kind: ConfigMap
metadata:
  name: supplyui-nginx-conf
  namespace: front
data:
  nginx.conf: |-
    worker_processes  4;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format main '{ "@timestamp": "$time_iso8601", '
                     '"remote_addr": "$remote_addr", '
                     '"remote_user": "$remote_user", '
                     '"body_bytes_sent": "$body_bytes_sent", '
                     '"request_time": "$request_time", '
                     '"status": "$status", '
                     '"host": "$host", '
                     '"server_addr": "$server_addr",'
                     '"request": "$request", '
                     '"request_method": "$request_method", '
                     '"uri": "$uri", '
                     '"http_referrer": "$http_referer", '
                     '"http_x_forwarded_for": "$http_x_forwarded_for", '
                     '"http_user_agent": "$http_user_agent", '
                     '"upstreampstatus": "$upstream_status",'
                     '"upstreamaddr": "$upstream_addr",'
                     '"upstreamresponsetime": "$upstream_response_time"'
                '}';

        access_log  logs/access.log  main;

        sendfile        on;
        keepalive_timeout  65;
        keepalive_requests 8192;
        client_header_timeout 60s;
        client_body_timeout 60s;
        send_timeout 60;
        client_max_body_size 100m;

        gzip  on;
        gzip_min_length 1k;
        gzip_buffers    4   32k;
        gzip_http_version  1.1;
        gzip_comp_level   9;
        gzip_types   text/css  text/xml   applocation/javascript;
        gzip_vary  on;

        proxy_buffering on;
        proxy_buffer_size 64k;
        proxy_buffers 8 32k;
        proxy_temp_path proxy_temp 1 2;
        proxy_max_temp_file_size 1024m;
        proxy_temp_file_write_size 128k;
        #proxy_request_buffering on;
        proxy_ignore_headers Set-Cookie;
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        server {
            listen 80;
            server_name localhost;
            index index.html index.htm;
            root /usr/local/openresty/nginx/html;

            location / {
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
            }

        }

    }