apiVersion: v1
kind: PersistentVolume
metadata:
  name: b2bic-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /b2bic
    server: 172.16.80.25
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b2bic-pvc
  namespace: front
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi