apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yqm-admin
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - 'dhxt.shixh.com'
    - secretName: 'ssl-sxh'
  rules:
    - host: 'dhxt.shixh.com'
      http:
        paths:
          - backend:
              serviceName: yqm-admin
              servicePort: 8080
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: yqm-admin
  namespace: ops
  labels:
    app: yqm-admin
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
---
kind: Endpoints
apiVersion: v1
metadata:
  name: yqm-admin
  namespace: ops
subsets:
  - addresses:
      - ip: 172.16.64.13
    ports:
      - port: 8080