apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxljob
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
    - hosts:
        - 'xxljob.shixhsit.com'
    - secretName: 'ssl-sxh'
  rules:
    - host: 'xxljob.shixhsit.com'
      http:
        paths:
          - backend:
              serviceName: xxljob
              servicePort: 8080
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: xxljob
  namespace: ops
  labels:
    app: xxljob
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: xxljob
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: xxljob
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxljob
  template:
    metadata:
      labels:
        app: xxljob
    spec:
      containers:
        - name: xxljob
          imagePullPolicy: IfNotPresent
          image: harbor.shixhlocal.com/library/xxl-job:2.0.2-SNAPSHOT
          resources:
            limits:
              cpu: 0.3
              memory: 1000Mi
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: >-
                -server
                -XX:ActiveProcessorCount=1
                -Dspring.datasource.url=jdbc:mysql://10.50.4.114:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
                -Dspring.datasource.username=bl_sxh_dev_user
                -Dspring.datasource.password=nAFHbchS
                -Dxxl.job.accessToken=FuZpyVhPs50NWllkY3hcG79l0Vs2Uuv8sit
          volumeMounts:
            - name: app-logs
              mountPath: /data
            - name: volume-time
              mountPath: /etc/localtime
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: volume-time
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai