apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxljob
  namespace: ops
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: 'xxljob.jq.cn'
      http:
        paths:
          - backend:
              serviceName: xxljob
              servicePort: 8080
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: xxljob
  namespace: ops
  labels:
    app: xxljob
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: xxljob
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: xxljob
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxljob
  template:
    metadata:
      labels:
        app: xxljob
    spec:
      containers:
        - name: xxljob
          imagePullPolicy: IfNotPresent
          image: xuxueli/xxl-job-admin:2.1.2
          ports:
            - containerPort: 8080
          env:
            - name: PARAMS
              valueFrom:
                secretKeyRef:
                  name: xxljob
                  key: params
          volumeMounts:
            - name: app-logs
              mountPath: /data
      volumes:
        - name: app-logs
          emptyDir: {}